services:
  reservations: 
    build: 
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb+srv://mahbubrazashihab:mahbubrazashihab@cluster1.9onwmhg.mongodb.net/?retryWrites=true&w=majority